config/routes.rb
Rails.application.routes.draw do
  resources :vinyls do
    collection { post :import }
  end
  root 'vinyls#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vinyl.rb
class Vinyl < ApplicationRecord
  #export CSV
  def self.to_csv(fields = column_names, options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |vinyl|
        csv << vinyl.attributes.values_at(*fields)
      end
    end
  end
  #import CSV
  def self.import(file)
    CSV.foreach(file.path, headers: true, :quote_char => "\'") do |row|
      vinyl_hash = row.to_hash
      vinyl = find_or_create_by!(catalog: vinyl_hash['catalog'], artist: vinyl_hash['artist'], title: vinyl_hash['title'], label: vinyl_hash['label'], format: vinyl_hash['format'], rating: vinyl_hash['rating'], released: vinyl_hash['released'], release_id: vinyl_hash['release_id'], notes: vinyl_hash['notes'], date: vinyl_hash['date'])
      vinyl.update_attributes(vinyl_hash)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vinyls_controller.rb
class VinylsController < ApplicationController
  before_action :set_vinyl, only: [:show, :edit, :update, :destroy]

  # GET /vinyls
  # GET /vinyls.json
  def index
    @vinyls = Vinyl.all
    respond_to do |format|
      format.html
      format.csv { send_data @vinyls.to_csv(['catalog','artist', 'title', 'label', 'format', 'rating', 'released', 'release_id', 'notes', 'date']) }
    end
  end

  # GET /vinyls/1
  # GET /vinyls/1.json
  def show
  end

  # GET /vinyls/new
  def new
    @vinyl = Vinyl.new
  end

  # GET /vinyls/1/edit
  def edit
  end

  # POST /vinyls
  # POST /vinyls.json
  def create
    @vinyl = Vinyl.new(vinyl_params)

    respond_to do |format|
      if @vinyl.save
        format.html { redirect_to @vinyl, notice: 'Vinyl was successfully created.' }
        format.json { render :show, status: :created, location: @vinyl }
      else
        format.html { render :new }
        format.json { render json: @vinyl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vinyls/1
  # PATCH/PUT /vinyls/1.json
  def update
    respond_to do |format|
      if @vinyl.update(vinyl_params)
        format.html { redirect_to @vinyl, notice: 'Vinyl was successfully updated.' }
        format.json { render :show, status: :ok, location: @vinyl }
      else
        format.html { render :edit }
        format.json { render json: @vinyl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vinyls/1
  # DELETE /vinyls/1.json
  def destroy
    @vinyl.destroy
    respond_to do |format|
      format.html { redirect_to vinyls_url, notice: 'Vinyl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Vinyl.import(params[:file])
    redirect_to root_path, notice: "vinyls imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vinyl
      @vinyl = Vinyl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vinyl_params
      params.require(:vinyl).permit(:catalog, :artist, :title, :label, :format, :rating, :released, :release_id, :notes, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vinyls_helper.rb
module VinylsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSVU</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vinyls/_form.html.erb
<%= form_for(vinyl) do |f| %>
  <% if vinyl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vinyl.errors.count, "error") %> prohibited this vinyl from being saved:</h2>

      <ul>
      <% vinyl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :catalog %>
    <%= f.text_field :catalog %>
  </div>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :label %>
    <%= f.text_field :label %>
  </div>

  <div class="field">
    <%= f.label :format %>
    <%= f.text_field :format %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :released %>
    <%= f.number_field :released %>
  </div>

  <div class="field">
    <%= f.label :release_id %>
    <%= f.number_field :release_id %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vinyls/edit.html.erb
<h1>Editing Vinyl</h1>

<%= render 'form', vinyl: @vinyl %>

<%= link_to 'Show', @vinyl %> |
<%= link_to 'Back', vinyls_path %>

app/views/vinyls/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Vinyls</h1>

  <%= form_tag import_vinyls_path, multipart: true, class: 'form-inline' do %>

    <div class="form-group">
      <%= link_to "Export CSV", vinyls_path(format: :csv), class: 'btn btn-primary' %>
    </div>

    <div class="form-group">
      <%= file_field_tag :file, class: '' %>
    </div>

    <div class="form-group">
      <%= submit_tag "Import CSV", class: 'btn btn-info' %>
    </div>

  <% end %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Catalog</th>
        <th>Artist</th>
        <th>Title</th>
        <th>Label</th>
        <th>Format</th>
        <th>Rating</th>
        <th>Released</th>
        <th>Release</th>
        <th>Notes</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @vinyls.each do |vinyl| %>
        <tr>
          <td><%= vinyl.catalog %></td>
          <td><%= vinyl.artist %></td>
          <td><%= vinyl.title %></td>
          <td><%= vinyl.label %></td>
          <td><%= vinyl.format %></td>
          <td><%= vinyl.rating %></td>
          <td><%= vinyl.released %></td>
          <td><%= vinyl.release_id %></td>
          <td><%= vinyl.notes %></td>
          <td><%= vinyl.date %></td>
          <td><%= link_to 'Show', vinyl %></td>
          <td><%= link_to 'Edit', edit_vinyl_path(vinyl) %></td>
          <td><%= link_to 'Destroy', vinyl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Vinyl', new_vinyl_path, class:"btn btn-primary" %>

</div>

app/views/vinyls/new.html.erb
<h1>New Vinyl</h1>

<%= render 'form', vinyl: @vinyl %>

<%= link_to 'Back', vinyls_path %>

app/views/vinyls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Catalog:</strong>
  <%= @vinyl.catalog %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @vinyl.artist %>
</p>

<p>
  <strong>Title:</strong>
  <%= @vinyl.title %>
</p>

<p>
  <strong>Label:</strong>
  <%= @vinyl.label %>
</p>

<p>
  <strong>Format:</strong>
  <%= @vinyl.format %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @vinyl.rating %>
</p>

<p>
  <strong>Released:</strong>
  <%= @vinyl.released %>
</p>

<p>
  <strong>Release:</strong>
  <%= @vinyl.release_id %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @vinyl.notes %>
</p>

<p>
  <strong>Date:</strong>
  <%= @vinyl.date %>
</p>

<%= link_to 'Edit', edit_vinyl_path(@vinyl) %> |
<%= link_to 'Back', vinyls_path %>